// Code generated by protoc-gen-go.
// source: myrpc.proto
// DO NOT EDIT!

/*
Package myrpc is a generated protocol buffer package.

It is generated from these files:
	myrpc.proto

It has these top-level messages:
	CreatePersonRequest
	CreatePersonResponse
	GetPersonRequest
	GetPersonResponse
*/
package myrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CreatePersonRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *CreatePersonRequest) Reset()                    { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()               {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreatePersonResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreatePersonResponse) Reset()                    { *m = CreatePersonResponse{} }
func (m *CreatePersonResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePersonResponse) ProtoMessage()               {}
func (*CreatePersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetPersonRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetPersonRequest) Reset()                    { *m = GetPersonRequest{} }
func (m *GetPersonRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPersonRequest) ProtoMessage()               {}
func (*GetPersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetPersonResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *GetPersonResponse) Reset()                    { *m = GetPersonResponse{} }
func (m *GetPersonResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPersonResponse) ProtoMessage()               {}
func (*GetPersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CreatePersonRequest)(nil), "myrpc.CreatePersonRequest")
	proto.RegisterType((*CreatePersonResponse)(nil), "myrpc.CreatePersonResponse")
	proto.RegisterType((*GetPersonRequest)(nil), "myrpc.GetPersonRequest")
	proto.RegisterType((*GetPersonResponse)(nil), "myrpc.GetPersonResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for People service

type PeopleClient interface {
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error)
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
}

type peopleClient struct {
	cc *grpc.ClientConn
}

func NewPeopleClient(cc *grpc.ClientConn) PeopleClient {
	return &peopleClient{cc}
}

func (c *peopleClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error) {
	out := new(CreatePersonResponse)
	err := grpc.Invoke(ctx, "/myrpc.People/CreatePerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := grpc.Invoke(ctx, "/myrpc.People/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for People service

type PeopleServer interface {
	CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error)
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
}

func RegisterPeopleServer(s *grpc.Server, srv PeopleServer) {
	s.RegisterService(&_People_serviceDesc, srv)
}

func _People_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PeopleServer).CreatePerson(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _People_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PeopleServer).GetPerson(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _People_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myrpc.People",
	HandlerType: (*PeopleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _People_CreatePerson_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _People_GetPerson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xad, 0x2c, 0x2a,
	0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x64, 0xd2, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32,
	0xf3, 0xf3, 0x8a, 0x21, 0x8a, 0x94, 0xac, 0xb9, 0x84, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x03,
	0x52, 0x8b, 0x8a, 0xf3, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e,
	0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0xa0, 0x10, 0x6b, 0x10, 0x88, 0xa9, 0xa4, 0xc7, 0x25, 0x82,
	0xaa, 0xb9, 0xb8, 0x00, 0x68, 0x72, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e,
	0x09, 0x54, 0x3f, 0x94, 0xa7, 0xa4, 0xc6, 0x25, 0xe0, 0x9e, 0x5a, 0x42, 0xd0, 0x26, 0x25, 0x4b,
	0x2e, 0x41, 0x24, 0x75, 0x50, 0x43, 0x89, 0x72, 0x92, 0xd1, 0x69, 0x46, 0x2e, 0xb6, 0x80, 0xd4,
	0xfc, 0x82, 0x9c, 0x54, 0xa1, 0x24, 0x2e, 0x1e, 0x64, 0xd7, 0x09, 0x49, 0xe9, 0x41, 0x42, 0x07,
	0x8b, 0x7f, 0xa5, 0xa4, 0xb1, 0xca, 0x41, 0x6c, 0x56, 0x92, 0x6c, 0xba, 0xfc, 0x64, 0x32, 0x93,
	0xb0, 0x12, 0x1f, 0x38, 0x0c, 0xcb, 0x0c, 0xf5, 0x0b, 0xc0, 0x16, 0x58, 0x31, 0x6a, 0x09, 0xc5,
	0x72, 0x71, 0xc2, 0x5d, 0x2a, 0x24, 0x0e, 0x35, 0x04, 0xdd, 0x8f, 0x52, 0x12, 0x98, 0x12, 0x50,
	0xa3, 0x65, 0xc1, 0x46, 0x8b, 0x0b, 0x89, 0xa2, 0x1a, 0xad, 0x5f, 0x0d, 0xf2, 0x5e, 0x6d, 0x12,
	0x1b, 0x38, 0x92, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xfb, 0x30, 0x1d, 0xd8, 0x01,
	0x00, 0x00,
}
