// Code generated by protoc-gen-go.
// source: myrpc.proto
// DO NOT EDIT!

/*
Package myrpc is a generated protocol buffer package.

It is generated from these files:
	myrpc.proto

It has these top-level messages:
	CreatePersonRequest
	CreatePersonResponse
	GetPersonRequest
	GetPersonResponse
	EmptyMessage
*/
package myrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CreatePersonRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *CreatePersonRequest) Reset()                    { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()               {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreatePersonResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreatePersonResponse) Reset()                    { *m = CreatePersonResponse{} }
func (m *CreatePersonResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePersonResponse) ProtoMessage()               {}
func (*CreatePersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetPersonRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetPersonRequest) Reset()                    { *m = GetPersonRequest{} }
func (m *GetPersonRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPersonRequest) ProtoMessage()               {}
func (*GetPersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetPersonResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *GetPersonResponse) Reset()                    { *m = GetPersonResponse{} }
func (m *GetPersonResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPersonResponse) ProtoMessage()               {}
func (*GetPersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*CreatePersonRequest)(nil), "myrpc.CreatePersonRequest")
	proto.RegisterType((*CreatePersonResponse)(nil), "myrpc.CreatePersonResponse")
	proto.RegisterType((*GetPersonRequest)(nil), "myrpc.GetPersonRequest")
	proto.RegisterType((*GetPersonResponse)(nil), "myrpc.GetPersonResponse")
	proto.RegisterType((*EmptyMessage)(nil), "myrpc.EmptyMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for People service

type PeopleClient interface {
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error)
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
	GetPeople(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (People_GetPeopleClient, error)
	FullDuplex(ctx context.Context, opts ...grpc.CallOption) (People_FullDuplexClient, error)
}

type peopleClient struct {
	cc *grpc.ClientConn
}

func NewPeopleClient(cc *grpc.ClientConn) PeopleClient {
	return &peopleClient{cc}
}

func (c *peopleClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error) {
	out := new(CreatePersonResponse)
	err := grpc.Invoke(ctx, "/myrpc.People/CreatePerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := grpc.Invoke(ctx, "/myrpc.People/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleClient) GetPeople(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (People_GetPeopleClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_People_serviceDesc.Streams[0], c.cc, "/myrpc.People/GetPeople", opts...)
	if err != nil {
		return nil, err
	}
	x := &peopleGetPeopleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type People_GetPeopleClient interface {
	Recv() (*GetPersonResponse, error)
	grpc.ClientStream
}

type peopleGetPeopleClient struct {
	grpc.ClientStream
}

func (x *peopleGetPeopleClient) Recv() (*GetPersonResponse, error) {
	m := new(GetPersonResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peopleClient) FullDuplex(ctx context.Context, opts ...grpc.CallOption) (People_FullDuplexClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_People_serviceDesc.Streams[1], c.cc, "/myrpc.People/FullDuplex", opts...)
	if err != nil {
		return nil, err
	}
	x := &peopleFullDuplexClient{stream}
	return x, nil
}

type People_FullDuplexClient interface {
	Send(*GetPersonRequest) error
	Recv() (*GetPersonResponse, error)
	grpc.ClientStream
}

type peopleFullDuplexClient struct {
	grpc.ClientStream
}

func (x *peopleFullDuplexClient) Send(m *GetPersonRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *peopleFullDuplexClient) Recv() (*GetPersonResponse, error) {
	m := new(GetPersonResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for People service

type PeopleServer interface {
	CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error)
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
	GetPeople(*EmptyMessage, People_GetPeopleServer) error
	FullDuplex(People_FullDuplexServer) error
}

func RegisterPeopleServer(s *grpc.Server, srv PeopleServer) {
	s.RegisterService(&_People_serviceDesc, srv)
}

func _People_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PeopleServer).CreatePerson(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _People_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PeopleServer).GetPerson(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _People_GetPeople_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PeopleServer).GetPeople(m, &peopleGetPeopleServer{stream})
}

type People_GetPeopleServer interface {
	Send(*GetPersonResponse) error
	grpc.ServerStream
}

type peopleGetPeopleServer struct {
	grpc.ServerStream
}

func (x *peopleGetPeopleServer) Send(m *GetPersonResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _People_FullDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeopleServer).FullDuplex(&peopleFullDuplexServer{stream})
}

type People_FullDuplexServer interface {
	Send(*GetPersonResponse) error
	Recv() (*GetPersonRequest, error)
	grpc.ServerStream
}

type peopleFullDuplexServer struct {
	grpc.ServerStream
}

func (x *peopleFullDuplexServer) Send(m *GetPersonResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *peopleFullDuplexServer) Recv() (*GetPersonRequest, error) {
	m := new(GetPersonRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _People_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myrpc.People",
	HandlerType: (*PeopleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _People_CreatePerson_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _People_GetPerson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPeople",
			Handler:       _People_GetPeople_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FullDuplex",
			Handler:       _People_FullDuplex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xad, 0x2c, 0x2a,
	0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x64, 0xd2, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32,
	0xf3, 0xf3, 0x8a, 0x21, 0x8a, 0x94, 0xac, 0xb9, 0x84, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x03,
	0x52, 0x8b, 0x8a, 0xf3, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e,
	0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0xa0, 0x10, 0x6b, 0x10, 0x88, 0xa9, 0xa4, 0xc7, 0x25, 0x82,
	0xaa, 0xb9, 0xb8, 0x00, 0x68, 0x72, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e,
	0x09, 0x54, 0x3f, 0x94, 0xa7, 0xa4, 0xc6, 0x25, 0xe0, 0x9e, 0x5a, 0x42, 0xd0, 0x26, 0x25, 0x4b,
	0x2e, 0x41, 0x24, 0x75, 0x50, 0x43, 0x89, 0x73, 0x12, 0x1f, 0x17, 0x8f, 0x6b, 0x6e, 0x41, 0x49,
	0xa5, 0x6f, 0x6a, 0x71, 0x31, 0x90, 0x6f, 0x74, 0x89, 0x89, 0x8b, 0x2d, 0x20, 0x35, 0xbf, 0x20,
	0x27, 0x55, 0x28, 0x89, 0x8b, 0x07, 0xd9, 0xb5, 0x42, 0x52, 0x7a, 0x90, 0xd0, 0xc2, 0xe2, 0x7f,
	0x29, 0x69, 0xac, 0x72, 0x10, 0x97, 0x28, 0x49, 0x36, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x58, 0x89,
	0x0f, 0x1c, 0xa6, 0x65, 0x86, 0xfa, 0x05, 0x60, 0x0b, 0xac, 0x18, 0xb5, 0x84, 0x62, 0xb9, 0x38,
	0xe1, 0x2e, 0x17, 0x12, 0x87, 0x1a, 0x82, 0xee, 0x67, 0x29, 0x09, 0x4c, 0x09, 0xa8, 0xd1, 0xb2,
	0x60, 0xa3, 0xc5, 0x85, 0x44, 0x51, 0x8d, 0xd6, 0xaf, 0x06, 0x79, 0xb7, 0x56, 0xc8, 0x0e, 0x6a,
	0x3c, 0xd8, 0x3f, 0xc2, 0x50, 0x53, 0x90, 0xfd, 0x8b, 0xc7, 0x68, 0x06, 0x03, 0x46, 0x21, 0x57,
	0x2e, 0x2e, 0xb7, 0xd2, 0x9c, 0x1c, 0x97, 0x52, 0xa0, 0xfe, 0x0a, 0x72, 0xdc, 0xc7, 0xa0, 0xc1,
	0x68, 0xc0, 0x98, 0xc4, 0x06, 0x4e, 0x3b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x45,
	0x79, 0x47, 0x6f, 0x02, 0x00, 0x00,
}
